config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'informations#index'
  resources :informations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/information.rb
class Information < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :title
    validates :fish
    validates :date_id
  end

  with_options numericality: { only_integer: true, greater_than_or_equal_to: 0, message: 'is invalid' }, allow_blank: true do
    validates :size
    validates :weight
    validates :number
  end

  with_options numericality: { other_than: 1 } do
    validates :prefecture_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '北海道'}, 
    {id: 3, name: '青森県'}, 
    {id: 4, name: '岩手県'},
    {id: 5, name: '宮城県'},
    {id: 6, name: '秋田県'}, 
    {id: 7, name: '山形県'},
    {id: 8, name: '福島県'}, 
    {id: 9, name: '茨城県'}, 
    {id: 10, name: '栃木県'},
    {id: 11, name: '群馬県'}, 
    {id: 12, name: '埼玉県'}, 
    {id: 13, name: '千葉県'},
    {id: 14, name: '東京都'}, 
    {id: 15, name: '神奈川県'}, 
    {id: 16, name: '新潟県'},
    {id: 17, name: '富山県'}, 
    {id: 18, name: '石川県'}, 
    {id: 19, name: '福井県'},
    {id: 20, name: '山梨県'}, 
    {id: 21, name: '長野県'}, 
    {id: 22, name: '岐阜県'},
    {id: 23, name: '静岡県'}, 
    {id: 24, name: '愛知県'}, 
    {id: 25, name: '三重県'},
    {id: 26, name: '滋賀県'}, 
    {id: 27, name: '京都府'}, 
    {id: 28, name: '大阪府'},
    {id: 29, name: '兵庫県'}, 
    {id: 30, name: '奈良県'}, 
    {id: 31, name: '和歌山県'},
    {id: 32, name: '鳥取県'}, 
    {id: 33, name: '島根県'}, 
    {id: 34, name: '岡山県'},
    {id: 35, name: '広島県'}, 
    {id: 36, name: '山口県'}, 
    {id: 37, name: '徳島県'},
    {id: 38, name: '香川県'}, 
    {id: 39, name: '愛媛県'}, 
    {id: 40, name: '高知県'},
    {id: 41, name: '福岡県'}, 
    {id: 42, name: '佐賀県'}, 
    {id: 43, name: '長崎県'},
    {id: 44, name: '熊本県'}, 
    {id: 45, name: '大分県'}, 
    {id: 46, name: '宮崎県'},
    {id: 47, name: '鹿児島県'}, 
    {id: 48, name: '沖縄県'}
  ]
 
   include ActiveHash::Associations
   has_many :informations
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :informations

  with_options presence: true do
    validates :nickname

    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  def index
    @informations = Information.all.order("created_at DESC")
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    if @information.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    if @information.update(information_params)
      redirect_to root_path
    else
      render :edit
    end  
  end

  def destroy
    @information.destroy
    redirect_to root_path
  end

  private

  def information_params
    params.require(:information).permit(:image, :title, :text, :date_id, :fish, :size, :weight, :number, :prefecture_id, :area).merge(user_id: current_user.id)
  end

  def set_information
    @information = Information.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/edit.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">釣果を入力</h2>
    <%= form_with model: @information, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    
    <div class="new-items">
      <div class="weight-bold-text">
        釣果情報
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"釣果情報（必須 40文字まで)  例(タイが釣れました。)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          釣果情報の説明
          <span class="any-add">任意</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"釣果情報の説明（任意 1,000文字まで）  例(休日に堤防で釣りをしていたところタイが釣れました。)" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    
    <div class="items-detail">
      <div class="fish-information">釣果データ</div>
      <div class="form">
        <div class="weight-bold-text">
          釣れた日
          <span class="indispensable">必須</span>
        </div>
          <div class='input-date_id'>
            <%= f.datetime_field :date_id, class:"items-data_id", id:"item-name" %>
          </div>
        <div class="weight-bold-text">
          魚種
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :fish, class:"items-fish", id:"item-name", placeholder:"（必須 20文字まで)", maxlength:"20" %>
        <div class="weight-bold-text">
          サイズ
          <span class="any-add">任意</span>
        </div>
        <%= f.number_field :size, class:"items-size", id:"item-name" %><span class="size-cm"> cm</span>
        <div class="weight-bold-text">
          重さ
          <span class="any-add">任意</span>
        </div>
        <%= f.number_field :weight, class:"items-weight", id:"item-name" %><span class="weight-Kg"> Kg</span>
        <div class="weight-bold-text">
          匹数
          <span class="any-add">任意</span>
        </div>
        <%= f.number_field :number, class:"items-number", id:"item-name", maxlength:"3" %><span class="number-fish"> 匹</span>
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          エリア
          <span class="any-add">任意</span>
        </div>
        <%= f.text_field :area, class:"items-area", id:"item-name", placeholder:"（必須 20文字まで)", maxlength:"20" %>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/informations/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='title-contents'>
    <h2 class='service-title'>
      釣りを楽しもう
    </h2>
    <p class='service-explain'>
      fishingはだれでもかんたんに投稿できる
    </p>
    <p class='service-explain'>
      釣果情報アプリです
    </p>
  </div>
  
  <div class='select-reason-contents'>
    <h2 class='title'>
      釣りの注意点
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "Ifishing.jpeg", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          毒魚がよく釣れます！
        </h3>
        <p class='reason-list-description'>
          初心者の方は魚を素手で触れないようにしましょう。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "Jfishing.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          危険な場所に行かない！
        </h3>
        <p class='reason-list-description'>
          釣りは危険がいっぱいです。釣り場には注意しましょう。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "Kfishing.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          体調に気をつけよう！
        </h3>
        <p class='reason-list-description'>
          釣りでは熱中症が特に危険です。自分の体調には十分注意しましょう。
        </p>
      </li>
    </ul>
  </div>
  
  <div class='item-contents'>
    <h2 class='title'>釣果情報</h2>
    <%= link_to '新規投稿', new_information_path, class: "subtitle" %>
    <ul class='item-lists'>

      
      <% @informations.each do |information| %>
        <li class='list'>
          <%= link_to information_path(information.id) do %>
          <div class='item-img-content'>
            <%= image_tag information.image, class: "item-img" %>

          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= information.title %>
            </h3>
            <div class='item-price'>
              <%= information.date_id %>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>

      <% if @informations.length == 0 %>
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "Lfishing.png", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              投稿してね！
            </h3>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to(new_information_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'sakana11.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/informations/new.html.erb
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">釣果を入力</h2>
    <%= form_with model: @information, url: informations_path, method: :post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    
    <div class="new-items">
      <div class="weight-bold-text">
        釣果情報
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"釣果情報（必須 40文字まで)  例(タイが釣れました。)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          釣果情報の説明
          <span class="any-add">任意</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"釣果情報の説明（任意 1,000文字まで）  例(休日に堤防で釣りをしていたところタイが釣れました。)" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    
    <div class="items-detail">
      <div class="fish-information">釣果データ</div>
      <div class="form">
        <div class="weight-bold-text">
          釣れた日
          <span class="indispensable">必須</span>
        </div>
          <div class='input-date_id'>
            <%= f.datetime_field :date_id, class:"items-data_id", id:"item-name" %>
          </div>
        <div class="weight-bold-text">
          魚種
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :fish, class:"items-fish", id:"item-name", placeholder:"（必須 20文字まで)", maxlength:"20" %>
        <div class="weight-bold-text">
          サイズ
          <span class="any-add">任意</span>
        </div>
        <%= f.number_field :size, class:"items-size", id:"item-name" %><span class="size-cm"> cm</span>
        <div class="weight-bold-text">
          重さ
          <span class="any-add">任意</span>
        </div>
        <%= f.number_field :weight, class:"items-weight", id:"item-name" %><span class="weight-Kg"> Kg</span>
        <div class="weight-bold-text">
          匹数
          <span class="any-add">任意</span>
        </div>
        <%= f.number_field :number, class:"items-number", id:"item-name", maxlength:"3" %><span class="number-fish"> 匹</span>
        <div class="weight-bold-text">
          都道府県
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          エリア
          <span class="any-add">任意</span>
        </div>
        <%= f.text_field :area, class:"items-area", id:"item-name", placeholder:"（必須 20文字まで)", maxlength:"20" %>
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

app/views/informations/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name-title">
      <%= @information.title %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @information.image ,class:"item-box-img" %>
    </div>
    <h2 class="name-text">
      <%= @information.text %>
    </h2>
  </div>

    <% if user_signed_in? %>
      <% if current_user.id == @information.user.id %>
        <%= link_to "投稿ページ編集", edit_information_path, method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", "#", method: :delete, class:"item-destroy" %>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= "釣果データ" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">釣れた日</th>
          <td class="detail-value"><%= @information.date_id %></td>
        </tr>
        <tr>
          <th class="detail-item">魚種</th>
          <td class="detail-value"><%= @information.fish %></td>
        </tr>
        <tr>
          <th class="detail-item">サイズ</th>
          <td class="detail-value"><%= @information.size %></td>
        </tr>
        <tr>
          <th class="detail-item">重さ</th>
          <td class="detail-value"><%= @information.weight %></td>
        </tr>
        <tr>
          <th class="detail-item">匹数</th>
          <td class="detail-value"><%= @information.number %></td>
        </tr>
        <tr>
          <th class="detail-item">都道府県</th>
          <td class="detail-value"><%= @information.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">エリア</th>
          <td class="detail-value"><%= @information.area %></td>
        </tr>
      </tbody>
    </table>
    <%=link_to 'もどる', root_path, class:"show-back-btn" %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all'  %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='ad-footer-contents'>
  <h2 class='maxim'>
      「釣りの格言」
  </h2>
  <div class =text-block>
    <ul>
      <li class="text is-active">釣れない時は魚が考える時間を与えてくれた与えてくれたと思えばいい</li>
      <li class="text">釣り人は、どんな冒険家よりも先回りしてそこにいる</li>
      <li class="text">釣りは盗むもんだ、聞くもんじゃない</li>
      <li class="text">魚釣りは数字のようなものだ。というのは、完全にマスターできないからだ</li>
    </ul>
  </div>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='nav'>
    <ul class='lists-left'>
      <div class='search-bar-contents'>
        <p class="fishing-title">Fishing</p>
        <%= link_to image_tag("sakana11.png", class:"furima-icon"), "/" %>
      </div>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>